# Generated by Django 4.2.7 on 2025-12-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_populate_public_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='generated_display_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
