# Generated by Django 4.2.7 on 2025-12-25 15:42

from django.db import migrations
import random


def generate_fake_display_name(email):
    """Generate a fake display name based on the first two letters of email"""
    if not email or len(email) < 2:
        return "Anonymous User"
    
    # Get first two letters (lowercase)
    first_letter = email[0].lower()
    second_letter = email[1].lower() if len(email) > 1 else 'a'
    
    # Word mappings for first letter (adjectives/nouns)
    first_words = {
        'a': ['Ancient', 'Amazing', 'Artistic', 'Aurora', 'Astral'],
        'b': ['Brilliant', 'Bold', 'Brave', 'Bright', 'Breezy'],
        'c': ['Creative', 'Clever', 'Cosmic', 'Crystal', 'Calm'],
        'd': ['Dynamic', 'Daring', 'Divine', 'Dazzling', 'Deep'],
        'e': ['Elegant', 'Epic', 'Ethereal', 'Energetic', 'Enchanted'],
        'f': ['Fantastic', 'Fierce', 'Floating', 'Frozen', 'Fiery'],
        'g': ['Guardian', 'Golden', 'Graceful', 'Glorious', 'Gentle'],
        'h': ['Heroic', 'Harmonious', 'Heavenly', 'Hidden', 'Humble'],
        'i': ['Infinite', 'Inspired', 'Icy', 'Illuminated', 'Intrepid'],
        'j': ['Jubilant', 'Jade', 'Journey', 'Jovial', 'Just'],
        'k': ['Keen', 'Kind', 'Knight', 'Kaleidoscope', 'Kinetic'],
        'l': ['Luminous', 'Legendary', 'Lively', 'Lucky', 'Lunar'],
        'm': ['Majestic', 'Mystic', 'Mighty', 'Melodic', 'Magical'],
        'n': ['Noble', 'Nebula', 'Natural', 'Nimble', 'Noble'],
        'o': ['Oceanic', 'Optimistic', 'Opulent', 'Original', 'Orbital'],
        'p': ['Powerful', 'Peaceful', 'Prismatic', 'Proud', 'Pure'],
        'q': ['Quiet', 'Quick', 'Quasar', 'Quaint', 'Quantum'],
        'r': ['Radiant', 'Rapid', 'Royal', 'Rustic', 'Rising'],
        's': ['Stellar', 'Swift', 'Sacred', 'Serene', 'Shining'],
        't': ['Titanic', 'Tranquil', 'Triumphant', 'Twilight', 'Thunder'],
        'u': ['Unique', 'Unstoppable', 'Ultimate', 'Universe', 'United'],
        'v': ['Valiant', 'Vibrant', 'Vast', 'Victorious', 'Vivid'],
        'w': ['Wise', 'Wild', 'Wondrous', 'Warm', 'Wandering'],
        'x': ['Xenial', 'Xenon', 'Xylophone', 'Xenial', 'Xenon'],
        'y': ['Youthful', 'Yearning', 'Yellow', 'Yonder', 'Yielding'],
        'z': ['Zealous', 'Zenith', 'Zephyr', 'Zestful', 'Zodiac'],
    }
    
    # Word mappings for second letter (nouns)
    second_words = {
        'a': ['Aurora', 'Angel', 'Apex', 'Artisan', 'Atlas'],
        'b': ['Beacon', 'Bard', 'Blade', 'Breeze', 'Bridge'],
        'c': ['Champion', 'Crystal', 'Comet', 'Crown', 'Cascade'],
        'd': ['Dragon', 'Dawn', 'Dream', 'Diamond', 'Destiny'],
        'e': ['Eagle', 'Echo', 'Empire', 'Essence', 'Eclipse'],
        'f': ['Flame', 'Falcon', 'Forest', 'Fortress', 'Fountain'],
        'g': ['Guardian', 'Gale', 'Gem', 'Glacier', 'Grove'],
        'h': ['Heights', 'Harbor', 'Horizon', 'Harmony', 'Haven'],
        'i': ['Island', 'Iris', 'Ivory', 'Inferno', 'Infinity'],
        'j': ['Jewel', 'Journey', 'Jungle', 'Jester', 'Jupiter'],
        'k': ['Keeper', 'Knight', 'Kingdom', 'Kite', 'Kraken'],
        'l': ['Light', 'Lion', 'Lagoon', 'Legend', 'Lighthouse'],
        'm': ['Mountain', 'Moon', 'Mist', 'Monarch', 'Mirage'],
        'n': ['Nexus', 'Night', 'Nova', 'Nest', 'Nymph'],
        'o': ['Oracle', 'Ocean', 'Oasis', 'Orbit', 'Owl'],
        'p': ['Phoenix', 'Peak', 'Pinnacle', 'Portal', 'Prism'],
        'q': ['Quest', 'Quill', 'Quartz', 'Quiver', 'Quarry'],
        'r': ['Rider', 'River', 'Realm', 'Ridge', 'Raven'],
        's': ['Star', 'Storm', 'Summit', 'Sage', 'Serpent'],
        't': ['Tower', 'Tide', 'Throne', 'Tiger', 'Temple'],
        'u': ['Unicorn', 'Unity', 'Umbra', 'Urchin', 'Utopia'],
        'v': ['Voyager', 'Valley', 'Vortex', 'Vanguard', 'Vista'],
        'w': ['Warrior', 'Wave', 'Wind', 'Wolf', 'Warden'],
        'x': ['Xenon', 'Xerox', 'Xyst', 'Xenial', 'Xenon'],
        'y': ['Yonder', 'Yarn', 'Yew', 'Yacht', 'Yin'],
        'z': ['Zenith', 'Zephyr', 'Zone', 'Zodiac', 'Zest'],
    }
    
    # Get words based on letters
    first_word_options = first_words.get(first_letter, ['Mysterious'])
    second_word_options = second_words.get(second_letter, ['User'])
    
    # Randomly select from options for variety
    first_word = random.choice(first_word_options)
    second_word = random.choice(second_word_options)
    
    return f"{first_word} {second_word}"


def populate_generated_display_names(apps, schema_editor):
    """Populate generated_display_name for all existing UserProfile instances"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    for profile in UserProfile.objects.filter(generated_display_name=''):
        if profile.user.email:
            profile.generated_display_name = generate_fake_display_name(profile.user.email)
            profile.save(update_fields=['generated_display_name'])


def reverse_populate_generated_display_names(apps, schema_editor):
    """Reverse migration - clear generated_display_name"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.all().update(generated_display_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_generated_display_name'),
    ]

    operations = [
        migrations.RunPython(populate_generated_display_names, reverse_populate_generated_display_names),
    ]
