# Generated by Django 4.2.7 on 2025-12-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_populate_generated_display_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='show_real_name',
            field=models.BooleanField(default=False),
        ),
    ]
