# Generated by Django 4.2.7 on 2025-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='commands_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
