# Generated by Django 4.2.7 on 2025-12-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0002_alter_cubaseversion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='secret_token',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
