# Generated by Django 4.2.7 on 2025-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0002_macro_commands_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='xml_snippet',
            field=models.TextField(blank=True),
        ),
    ]
