# Generated by Django 4.2.7 on 2025-12-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0003_macro_secret_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='macro',
            unique_together=set(),
        ),
    ]
